##############
# CORE SETUP #
##############

# Supported models listed here https://github.com/neelnanda-io/TransformerLens/blob/main/transformer_lens/loading_from_pretrained.py
# model_name: "stabilityai/stablelm-base-alpha-3b"
# model_name: "meta-llama/Llama-2-7b-hf"
# model_name: "meta-llama/Llama-2-13b-hf"
# model_name: "gpt2-xl"
model_name: "gpt2-small"
experiment_notes: "Trying Eleni honesty contrastive with because."
prompts_sheet: "../data/inputs/honesty_contrastive_formatted_final.csv"
use_gpu: True
write_cache: False
enable_steering: True



############
# ANALYSIS #
############

# ToDo: Allow for option to run dimensionality reduction methods with and without classifiers
# ToDo: Allow for parameters to be set for classifiers

# To not run one of the dimensionality reduction methods, comment it out
# along with its parameters, eg
    # pca:
    #   n_components: 2
    #   random_state: 42

dim_red:
  methods:
    pca:
      n_components: 2
      random_state: 42
    tsne:
      n_components: 2
      perplexity: 30
    feature_agglomeration:
      n_clusters: 2

# To run one of the classifiers, comment it out, eg
    # logistic_regression:
# Note that currently all classifiers will be run
# with all the uncommented dimensionality reduction methods
# E.g. if pca, tsne, and feature_agglomeration are uncommented,
# then each classifiers will be run for each of them.

classifiers:
  methods:
    - logistic_regression
    - decision_tree
    - random_forest
    - svc
    - knn
    - gradient_boosting

other_dim_red_analyses:
  methods:
    - random_projections_analysis

non_dimensionality_reduction:
  methods:
    - raster_plot
    - probe_hidden_states
