model_name: gpt2-small
experiment_notes: Trying Eleni honesty contrastive with because.
prompts_sheet: ../data/inputs/honesty_contrastive_formatted_final.csv
use_gpu: true
write_cache: false
dim_red:
  methods:
    pca:
      n_components: 12
      random_state: 42
    feature_agglomeration:
      n_clusters: 3
classifiers:
  methods:
  - decision_tree
  - knn
other_dim_red_analyses:
  methods:
  - random_projections_analysis
non_dimensionality_reduction:
  methods:
  - probe_hidden_states
