model_name: gpt2-small
experiment_notes: Trying Eleni honesty contrastive with because.
prompts_sheet: ../data/inputs/honesty_contrastive_formatted_final.csv
use_gpu: true
write_cache: false
dim_red:
  methods:
    tsne:
      n_components: 6
      perplexity: 90
classifiers:
  methods:
  - decision_tree
  - svc
  - knn
other_dim_red_analyses:
  methods: []
non_dimensionality_reduction:
  methods:
  - raster_plot
  - probe_hidden_states
