# Supported models listed here https://github.com/neelnanda-io/TransformerLens/blob/main/transformer_lens/loading_from_pretrained.py
model_name: "gpt2-small"
experiment_notes: "Trying Eleni first set of prompts with because."
prompts_sheet: "../data/inputs/good_bad_interactive.csv"
use_gpu: False
write_cache: False
