##############
# CORE SETUP #
##############

# Supported models listed here https://github.com/neelnanda-io/TransformerLens/blob/main/transformer_lens/loading_from_pretrained.py
# model_name: "stabilityai/stablelm-base-alpha-3b"
# model_name: "meta-llama/Llama-2-7b-hf"
# model_name: "meta-llama/Llama-2-13b-hf"
# model_name: "gpt2-xl"
model_name: "gpt2-small"
experiment_notes: "Trying Eleni honesty contrastive with because."
prompts_sheet: "../data/inputs/honesty_contrastive_formatted_final.csv"
use_gpu: True
write_cache: False
enable_steering: True

dim_red:
  methods:
    pca:
      n_components: 2
      random_state: 42
    tsne:
      n_components: 2
      perplexity: 30
    feature_agglomeration:
      n_clusters: 2


classifiers:
  methods:
    - logistic_regression
    - decision_tree
    - random_forest
    - svc
    - knn
    - gradient_boosting

other_dim_red_analyses:
  methods:
    - random_projections_analysis

non_dimensionality_reduction:
  methods:
    - raster_plot
    - probe_hidden_states
