# model_name: meta-llama/Llama-2-7b-hf
model_name: "gpt2-small"
experiment_notes: Trying Eleni honesty contrastive with because.
# prompts_sheet: ../data/inputs/prompts_good_evil_justice.xlsx
prompts_sheet: "../data/inputs/honesty_contrastive_formatted_final.csv"
use_gpu: true
write_cache: false
evaluate_completion: true
steering:
  load: true
  write: true
  file: "../data/inputs/steering/gpt2-small_Good_PCA_rep_reader.pkl"
dim_red:
  methods:
    tsne:
      n_components: 2
      perplexity: 30
classifiers:
  methods:
  - knn
other_dim_red_analyses:
  methods:
  - random_projections_analysis
non_dimensionality_reduction:
  methods:
  - probe_hidden_states
