model_name: meta-llama/Llama-2-7b-hf
experiment_notes: Trying Eleni honesty contrastive with because.
prompts_sheet: ../data/inputs/honesty_contrastive_formatted_final.csv
use_gpu: true
write_cache: false
enable_steering: true
dim_red:
  methods:
    tsne:
      n_components: 2
      perplexity: 30
classifiers:
  methods:
  - knn
other_dim_red_analyses:
  methods:
  - random_projections_analysis
non_dimensionality_reduction:
  methods:
  - probe_hidden_states
