# model_name: "openai-community/gpt2"
model_name: "meta-llama/Llama-2-7b-chat-hf"
experiment_notes: Trying Eleni honesty contrastive with because.
prompts_sheet: ../data/inputs/honesty_contrastive_formatted_final.csv
use_gpu: true
write_cache: false
evaluate_completion: true
steering:
  load: true
  write: true
  file: ../data/inputs/steering/gpt2-small_Good_PCA_rep_reader.pkl
dim_red:
  methods:
    pca:
      n_components: 2
      random_state: 42
    tsne:
      n_components: 2
      perplexity: 30
    feature_agglomeration:
      n_clusters: 2
classifiers:
  methods:
  - knn
other_dim_red_analyses:
  methods:
  - random_projections_analysis
non_dimensionality_reduction:
  methods:
  - probe_hidden_states
