model_name: gpt2-small
experiment_notes: Trying Eleni honesty contrastive with because.
prompts_sheet: ../data/inputs/prompts/pairs_v1/generated_datasets/honesty_combined_dataset_fully_labelled.csv
use_gpu: true
write_cache: false
enable_steering: true
dim_red:
  methods:
    tsne:
      n_components: 2
      perplexity: 30
classifiers:
  methods:
  - knn
other_dim_red_analyses:
  methods:
  - random_projections_analysis
non_dimensionality_reduction:
  methods:
  - raster_plot
